---
title: "module_completeness"
author: "Lasse Steffensen"
date: "2026-02-18"
output: html_document
---

--------------------------------------------------------------------------------
                                    Pre    
--------------------------------------------------------------------------------

```{r}

setwd("C:/Users/lasse/Desktop/wd/25/01_05/module_completeness")

library(tidyverse)
library(reshape2)
library(colorspace)
library(ggtext)
library(ggalluvial)
library(scales)
library(ggh4x)
library(tibble)
library(tidytext)
library(patchwork)



# Annotation files
annotations <- read.csv("C:/Users/lasse/Desktop/wd/25/01_05/write_files/annotations_all.tsv", sep="\t", header=TRUE)

meso_annotations <- read.csv("C:/Users/lasse/Desktop/wd/25/01_05/write_files/meso_mags_annotations.tsv", sep="\t", header=TRUE)

thermo_annotations <- read.csv("C:/Users/lasse/Desktop/wd/25/01_05/write_files/thermo_mags_annotations.tsv", sep="\t", header=TRUE)


# Tax files
meso_tax <- read.csv("C:/Users/lasse/Desktop/wd/25/01_05/write_files/meso_mags_tax.tsv", sep="\t", header=TRUE)

thermo_tax <- read.csv("C:/Users/lasse/Desktop/wd/25/01_05/write_files/thermo_mags_tax.tsv", sep="\t", header=TRUE)


# Name map
name_map <- bind_rows(
  meso_tax %>% mutate(source = "meso"),
  thermo_tax %>% mutate(source = "thermo")
) %>%
  transmute(
    old = as.character(Genome),
    species = str_squish(species),
    genus   = str_squish(genus),
    family  = str_squish(family),
    new = case_when(
      !is.na(species) & species != "" ~ species,
      !is.na(genus)   & genus   != "" ~ paste0("g_", genus, " sp"),
      !is.na(family)  & family  != "" ~ paste0("f_", family, " sp"),
      TRUE ~ old
    ),
    source
  ) %>%
  arrange(old, desc(new != old), source) %>%
  distinct(old, .keep_all = TRUE) %>%
  select(old, new)


# Module file
modules <- read.csv("C:/Users/lasse/Desktop/wd/25/df/26/module_phase.tsv", sep="\t", header=TRUE)





```


Prepare dataframes for plotting
```{r}

# Concatenate files (Remove redundant variables and non-target modules)
meso_ann_tax <- meso_annotations %>%
  left_join(
    meso_tax %>% select(-rel_abun, -mean, -cov_frac), 
    by = "Genome") %>%
  left_join(modules, by = "module") %>%
  filter(!is.na(phase)) %>%
  left_join(name_map, by= c("Genome" = "old")) %>%
  mutate(sample = "meso")


thermo_ann_tax <- thermo_annotations %>%
  left_join(
    thermo_tax %>% select(-rel_abun, -mean, -cov_frac), 
    by = "Genome") %>%
  left_join(modules, by = "module") %>%
  filter(!is.na(phase)) %>%
  left_join(name_map, by= c("Genome" = "old")) %>%
  mutate(sample = "thermo")

joined_ann_tax <- bind_rows(meso_ann_tax, thermo_ann_tax)




```


Create tax-level rel abun labels
```{r}
### Genus-level
genus_abun_meso <- meso_tax %>%
  mutate(genus = na_if(genus, "")) %>%
  filter(!is.na(genus), !is.na(rel_abun)) %>%
  group_by(genus) %>%
  summarise(
    genus_r_abund = sum(rel_abun, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(sample = "meso")


genus_abun_thermo <- thermo_tax %>%
  mutate(genus = na_if(genus, "")) %>%
  filter(!is.na(genus), !is.na(rel_abun)) %>%
  group_by(genus) %>%
  summarise(
    genus_r_abund = sum(rel_abun, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(sample = "thermo")

genus_abun <- bind_rows(genus_abun_meso, genus_abun_thermo)


### Phylum-level
phylum_abun_meso <- meso_tax %>%
  mutate(phylum = na_if(phylum, "")) %>%
  filter(!is.na(phylum), !is.na(rel_abun)) %>%
  group_by(phylum) %>%
  summarise(
    phylum_r_abund = sum(rel_abun, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(sample = "meso")


phylum_abun_thermo <- thermo_tax %>%
  mutate(phylum = na_if(phylum, "")) %>%
  filter(!is.na(phylum), !is.na(rel_abun)) %>%
  group_by(phylum) %>%
  summarise(
    phylum_r_abund = sum(rel_abun, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(sample = "thermo")

phylum_abun <- bind_rows(phylum_abun_meso, phylum_abun_thermo)



```

#####################################################################################







                         Higher taxonomic level analysis
                             (mostly phylum-level)








#####################################################################################


Methanogenesis (genus-level)
```{r}

############################################################################################################
###                                             Meso                                                     ###
############################################################################################################


# Filter only by phase and sample
m <- joined_ann_tax %>%
  filter(phase == "Methanogenesis", sample == "meso") %>%
  mutate(genus = na_if(genus, "")) %>%
  filter(!is.na(genus))

# Use module order from modules
module_order_meth <- modules %>%
  filter(phase == "Methanogenesis") %>%
  pull(module)

# collapse to genus x module
m_genus0 <- m %>%
  group_by(Genome, genus, module) %>%
  summarise(p = max(Percent_steps_found, na.rm = TRUE), .groups = "drop") %>%
  group_by(genus, module) %>%  
  summarise(
    Percent_steps_found = max(p, na.rm = TRUE),
    n_genomes = n_distinct(Genome[p >= 50]), 
    .groups = "drop"
  )



# Force-show all modules by completing the grid
m_genus <- m_genus0 %>%
  mutate(module = factor(module, levels = module_order_meth)) %>%
  complete(
    genus,
    module,
    fill = list(
      Percent_steps_found = 0,  # empty = 0% completeness (will be invisible with alpha mapping below)
      n_genomes = 0
    )
  ) %>%
  ungroup()

m_genus <- m_genus %>%
  group_by(genus) %>%
  filter(any(Percent_steps_found >= 50, na.rm = TRUE)) %>%
  ungroup()

# Join genus abundance
m_genus <- m_genus %>%
  left_join(genus_abun %>% filter(sample == "meso"), by = "genus")

m_genus <- m_genus %>%
  mutate(
    alpha = case_when(
      is.na(Percent_steps_found)        ~ 0,
      Percent_steps_found < 50          ~ 0,  # hide <50% (set e.g. 0.05 if you want faint tiles)
      TRUE ~ scales::rescale(Percent_steps_found, from = c(50, 100), to = c(0.15, 1))
    )
  )

genus_labels <- genus_abun %>%
  filter(sample == "meso") %>%
  mutate(abun_lab = sprintf("%.1f%%", genus_r_abund)) %>%
  semi_join(m_genus %>% distinct(genus), by = "genus")



pm <- ggplot(m_genus, aes(x = module, y = genus)) +
  geom_tile(aes(alpha = alpha),
            fill = "mediumpurple4", color = NA, width = 0.9, height = 0.9) +
  scale_alpha(
    name   = "Module\ncompleteness",
    limits = c(0, 1),
    breaks = scales::rescale(c(50, 75, 100), from = c(50, 100), to = c(0.15, 1)),
    labels = c("50%", "75%", "100%"),
    range  = c(0, 1)
  ) +
  guides(alpha = guide_legend(override.aes = list(fill = "mediumpurple4"))) +
  geom_text(
    data = genus_labels,
    aes(x = -Inf, y = genus, label = abun_lab),
    inherit.aes = FALSE,
    hjust = 1,
    size = 3,
    colour = "black"
  ) +
  geom_text(aes(label = n_genomes), colour = "white", size = 3) +
  coord_cartesian(clip = "off") +
  theme_void() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 10),
    axis.text.y = element_text(size = 10, hjust = -0.35),
    axis.ticks  = element_line(color = "black"),
    axis.title  = element_blank(),
    legend.position = "right",
    panel.background = element_rect(fill = "white", color = NA),
    plot.background  = element_rect(fill = "white", color = NA),
    plot.margin = margin(t = 0, r = 20, b = 0, l = 60)
  )

pm





############################################################################################################
###                                             Thermo                                                   ###
############################################################################################################

# Filter only by phase and sample
m <- joined_ann_tax %>%
  filter(phase == "Methanogenesis", sample == "thermo") %>%
  mutate(genus = na_if(genus, "")) %>%
  filter(!is.na(genus))

# Use module order from modules
module_order_meth <- modules %>%
  filter(phase == "Methanogenesis") %>%
  pull(module)

# collapse to genus x module
m_genus0 <- m %>%
  group_by(Genome, genus, module) %>%
  summarise(p = max(Percent_steps_found, na.rm = TRUE), .groups = "drop") %>%
  group_by(genus, module) %>%  
  summarise(
    Percent_steps_found = max(p, na.rm = TRUE),
    n_genomes = n_distinct(Genome[p >= 50]), 
    .groups = "drop"
  )


# Force-show all modules by completing the grid
m_genus <- m_genus0 %>%
  mutate(module = factor(module, levels = module_order_meth)) %>%
  complete(
    genus,
    module,
    fill = list(
      Percent_steps_found = 0,  # empty = 0% completeness (will be invisible with alpha mapping below)
      n_genomes = 0
    )
  ) %>%
  ungroup()

m_genus <- m_genus %>%
  group_by(genus) %>%
  filter(any(Percent_steps_found >= 50, na.rm = TRUE)) %>%
  ungroup()

# Join genus abundance
m_genus <- m_genus %>%
  left_join(genus_abun %>% filter(sample == "thermo"), by = "genus")

m_genus <- m_genus %>%
  mutate(
    alpha = case_when(
      is.na(Percent_steps_found)        ~ 0,
      Percent_steps_found < 50          ~ 0,  # hide <50% (set e.g. 0.05 if you want faint tiles)
      TRUE ~ scales::rescale(Percent_steps_found, from = c(50, 100), to = c(0.15, 1))
    )
  )

genus_labels <- genus_abun %>%
  filter(sample == "thermo") %>%
  mutate(abun_lab = sprintf("%.1f%%", genus_r_abund)) %>%
  semi_join(m_genus %>% distinct(genus), by = "genus")



pt <- ggplot(m_genus, aes(x = module, y = genus)) +
  geom_tile(aes(alpha = alpha),
            fill = "mediumpurple4", color = NA, width = 0.9, height = 0.9) +
  scale_alpha(
    name   = "Module\ncompleteness",
    limits = c(0, 1),
    breaks = scales::rescale(c(50, 75, 100), from = c(50, 100), to = c(0.15, 1)),
    labels = c("50%", "75%", "100%"),
    range  = c(0, 1)
  ) +
  guides(alpha = guide_legend(override.aes = list(fill = "mediumpurple4"))) +
  geom_text(
    data = genus_labels,
    aes(x = -Inf, y = genus, label = abun_lab),
    inherit.aes = FALSE,
    hjust = 1,
    size = 3,
    colour = "black"
  ) +
  geom_text(aes(label = n_genomes), colour = "white", size = 3) +
  coord_cartesian(clip = "off") +
  theme_void() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 10),
    axis.text.y = element_text(size = 10, hjust = -0.35),
    axis.ticks  = element_line(color = "black"),
    axis.title  = element_blank(),
    legend.position = "right",
    panel.background = element_rect(fill = "white", color = NA),
    plot.background  = element_rect(fill = "white", color = NA),
    plot.margin = margin(t = 0, r = 20, b = 0, l = 60)
  )

pt


p <- pm | pt 


ggsave(filename = "higher_level/methanogenesis_genus.png", plot = p,
       width = 11, height = 6, dpi = 300)




```

Acidogenesis (phylum-level)
```{r}

############################################################################################################
###                                             Meso                                                     ###
############################################################################################################


# Filter only by phase and sample
acid <- joined_ann_tax %>%
  filter(phase == "Acidogenesis", sample == "meso") %>%
  mutate(phylum = na_if(phylum, "")) %>%
  filter(!is.na(phylum))

# Use module order from modules
module_order_acid <- modules %>%
  filter(phase == "Acidogenesis") %>%
  pull(module)

# collapse to genus x module
acid_phylum0 <- acid %>%
  group_by(Genome, phylum, module) %>%              # <-- MUST include module here
  summarise(p = max(Percent_steps_found, na.rm = TRUE), .groups = "drop") %>%
  group_by(phylum, module) %>%                      # <-- and here
  summarise(
    Percent_steps_found = max(p, na.rm = TRUE),
    n_genomes = n_distinct(Genome[p >= 50]),        # <-- per-module count
    .groups = "drop"
  )



# Force-show all modules by completing the grid
acid_phylum <- acid_phylum0 %>%
  mutate(module = factor(module, levels = module_order_acid)) %>%
  complete(
    phylum,
    module,
    fill = list(
      Percent_steps_found = 0,  # empty = 0% completeness (will be invisible with alpha mapping below)
      n_genomes = 0
    )
  ) %>%
  ungroup()

acid_phylum <- acid_phylum %>%
  group_by(phylum) %>%
  filter(any(Percent_steps_found >= 50, na.rm = TRUE)) %>%
  ungroup()

# Join genus abundance
acid_phylum <- acid_phylum %>%
  left_join(phylum_abun %>% filter(sample == "meso"), by = "phylum")

acid_phylum <- acid_phylum %>%
  mutate(
    alpha = case_when(
      is.na(Percent_steps_found)        ~ 0,
      Percent_steps_found < 50          ~ 0,  # hide <50% (set e.g. 0.05 if you want faint tiles)
      TRUE ~ scales::rescale(Percent_steps_found, from = c(50, 100), to = c(0.15, 1))
    )
  )

phylum_labels <- phylum_abun %>%
  filter(sample == "meso") %>%
  mutate(abun_lab = sprintf("%.1f%%", phylum_r_abund)) %>%
  semi_join(acid_phylum %>% distinct(phylum), by = "phylum")



acidm <- ggplot(acid_phylum, aes(x = module, y = phylum)) +
  geom_tile(aes(alpha = alpha),
            fill = "palegreen4", color = NA, width = 0.9, height = 0.9) +
  scale_alpha(
    name   = "Module\ncompleteness",
    limits = c(0, 1),
    breaks = scales::rescale(c(50, 75, 100), from = c(50, 100), to = c(0.15, 1)),
    labels = c("50%", "75%", "100%"),
    range  = c(0, 1)
  ) +
  guides(alpha = guide_legend(override.aes = list(fill = "palegreen4"))) +
  geom_text(
    data = phylum_labels,
    aes(x = -Inf, y = phylum, label = abun_lab),
    inherit.aes = FALSE,
    hjust = 1,
    size = 3,
    colour = "black"
  ) +
  geom_text(aes(label = n_genomes), colour = "white", size = 3) +
  coord_cartesian(clip = "off") +
  theme_void() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 10),
    axis.text.y = element_text(size = 10, hjust = -0.35),
    axis.ticks  = element_line(color = "black"),
    axis.title  = element_blank(),
    legend.position = "right",
    panel.background = element_rect(fill = "white", color = NA),
    plot.background  = element_rect(fill = "white", color = NA),
    plot.margin = margin(t = 0, r = 20, b = 0, l = 60)
  )

acidm





############################################################################################################
###                                             Thermo                                                   ###
############################################################################################################

# Filter only by phase and sample
acid <- joined_ann_tax %>%
  filter(phase == "Acidogenesis", sample == "thermo") %>%
  mutate(phylum = na_if(phylum, "")) %>%
  filter(!is.na(phylum))

# Use module order from modules
module_order_acid <- modules %>%
  filter(phase == "Acidogenesis") %>%
  pull(module)

# collapse to genus x module
acid_phylum0 <- acid %>%
  group_by(Genome, phylum, module) %>%              # <-- MUST include module here
  summarise(p = max(Percent_steps_found, na.rm = TRUE), .groups = "drop") %>%
  group_by(phylum, module) %>%                      # <-- and here
  summarise(
    Percent_steps_found = max(p, na.rm = TRUE),
    n_genomes = n_distinct(Genome[p >= 50]),        # <-- per-module count
    .groups = "drop"
  )



# Force-show all modules by completing the grid
acid_phylum <- acid_phylum0 %>%
  mutate(module = factor(module, levels = module_order_acid)) %>%
  complete(
    phylum,
    module,
    fill = list(
      Percent_steps_found = 0,  # empty = 0% completeness (will be invisible with alpha mapping below)
      n_genomes = 0
    )
  ) %>%
  ungroup()

acid_phylum <- acid_phylum %>%
  group_by(phylum) %>%
  filter(any(Percent_steps_found >= 50, na.rm = TRUE)) %>%
  ungroup()

# Join genus abundance
acid_phylum <- acid_phylum %>%
  left_join(phylum_abun %>% filter(sample == "thermo"), by = "phylum")

acid_phylum <- acid_phylum %>%
  mutate(
    alpha = case_when(
      is.na(Percent_steps_found)        ~ 0,
      Percent_steps_found < 50          ~ 0,  # hide <50% (set e.g. 0.05 if you want faint tiles)
      TRUE ~ scales::rescale(Percent_steps_found, from = c(50, 100), to = c(0.15, 1))
    )
  )

phylum_labels <- phylum_abun %>%
  filter(sample == "thermo") %>%
  mutate(abun_lab = sprintf("%.1f%%", phylum_r_abund)) %>%
  semi_join(acid_phylum %>% distinct(phylum), by = "phylum")



acidt <- ggplot(acid_phylum, aes(x = module, y = phylum)) +
  geom_tile(aes(alpha = alpha),
            fill = "palegreen4", color = NA, width = 0.9, height = 0.9) +
  scale_alpha(
    name   = "Module\ncompleteness",
    limits = c(0, 1),
    breaks = scales::rescale(c(50, 75, 100), from = c(50, 100), to = c(0.15, 1)),
    labels = c("50%", "75%", "100%"),
    range  = c(0, 1)
  ) +
  guides(alpha = guide_legend(override.aes = list(fill = "palegreen4"))) +
  geom_text(
    data = phylum_labels,
    aes(x = -Inf, y = phylum, label = abun_lab),
    inherit.aes = FALSE,
    hjust = 1,
    size = 3,
    colour = "black"
  ) +
  geom_text(aes(label = n_genomes), colour = "white", size = 3) +
  coord_cartesian(clip = "off") +
  theme_void() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 10),
    axis.text.y = element_text(size = 10, hjust = -0.35),
    axis.ticks  = element_line(color = "black"),
    axis.title  = element_blank(),
    legend.position = "right",
    panel.background = element_rect(fill = "white", color = NA),
    plot.background  = element_rect(fill = "white", color = NA),
    plot.margin = margin(t = 0, r = 20, b = 0, l = 60)
  )

acidt


acid <- acidm / acidt 


ggsave(filename = "higher_level/acidogenesis_phylum.png", plot = acid,
       width = 20, height = 15, dpi = 300)


```

Acetogenesis (phylum-level)
```{r}


############################################################################################################
###                                             Meso                                                     ###
############################################################################################################


# Filter only by phase and sample
acet <- joined_ann_tax %>%
  filter(phase == "Acetogenesis", sample == "meso") %>%
  mutate(phylum = na_if(phylum, "")) %>%
  filter(!is.na(phylum))

# Use module order from modules
module_order_acet <- modules %>%
  filter(phase == "Acetogenesis") %>%
  pull(module)

# collapse to genus x module
acet_phylum0 <- acet %>%
  group_by(Genome, phylum, module) %>%
  summarise(p = max(Percent_steps_found, na.rm = TRUE), .groups = "drop") %>%
  group_by(phylum, module) %>% 
  summarise(
    Percent_steps_found = max(p, na.rm = TRUE),
    n_genomes = n_distinct(Genome[p >= 50]),
    .groups = "drop"
  )



# Force-show all modules by completing the grid
acet_phylum <- acet_phylum0 %>%
  mutate(module = factor(module, levels = module_order_acet)) %>%
  complete(
    phylum,
    module,
    fill = list(
      Percent_steps_found = 0,  # empty = 0% completeness (will be invisible with alpha mapping below)
      n_genomes = 0
    )
  ) %>%
  ungroup()

acet_phylum <- acet_phylum %>%
  group_by(phylum) %>%
  filter(any(Percent_steps_found >= 50, na.rm = TRUE)) %>%
  ungroup()

# Join genus abundance
acet_phylum <- acet_phylum %>%
  left_join(phylum_abun %>% filter(sample == "meso"), by = "phylum")

acet_phylum <- acet_phylum %>%
  mutate(
    alpha = case_when(
      is.na(Percent_steps_found)        ~ 0,
      Percent_steps_found < 50          ~ 0,
      TRUE ~ scales::rescale(Percent_steps_found, from = c(50, 100), to = c(0.15, 1))
    )
  )

phylum_labels <- phylum_abun %>%
  filter(sample == "meso") %>%
  mutate(abun_lab = sprintf("%.1f%%", phylum_r_abund)) %>%
  semi_join(acet_phylum %>% distinct(phylum), by = "phylum")



acetm <- ggplot(acet_phylum, aes(x = module, y = phylum)) +
  geom_tile(aes(alpha = alpha),
            fill = "palevioletred4", color = NA, width = 0.9, height = 0.9) +
  scale_alpha(
    name   = "Module\ncompleteness",
    limits = c(0, 1),
    breaks = scales::rescale(c(50, 75, 100), from = c(50, 100), to = c(0.15, 1)),
    labels = c("50%", "75%", "100%"),
    range  = c(0, 1)
  ) +
  guides(alpha = guide_legend(override.aes = list(fill = "palevioletred4"))) +
  geom_text(
    data = phylum_labels,
    aes(x = -Inf, y = phylum, label = abun_lab),
    inherit.aes = FALSE,
    hjust = 1,
    size = 3,
    colour = "black"
  ) +
  geom_text(aes(label = n_genomes), colour = "white", size = 3) +
  coord_cartesian(clip = "off") +
  theme_void() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 10),
    axis.text.y = element_text(size = 10, hjust = -0.35),
    axis.ticks  = element_line(color = "black"),
    axis.title  = element_blank(),
    legend.position = "right",
    panel.background = element_rect(fill = "white", color = NA),
    plot.background  = element_rect(fill = "white", color = NA),
    plot.margin = margin(t = 0, r = 20, b = 0, l = 60)
  )

acetm





############################################################################################################
###                                             Thermo                                                   ###
############################################################################################################

# Filter only by phase and sample
acet <- joined_ann_tax %>%
  filter(phase == "Acetogenesis", sample == "thermo") %>%
  mutate(phylum = na_if(phylum, "")) %>%
  filter(!is.na(phylum))

# Use module order from modules
module_order_acet <- modules %>%
  filter(phase == "Acetogenesis") %>%
  pull(module)

# collapse to genus x module
acet_phylum0 <- acet %>%
  group_by(Genome, phylum, module) %>%    
  summarise(p = max(Percent_steps_found, na.rm = TRUE), .groups = "drop") %>%
  group_by(phylum, module) %>%     
  summarise(
    Percent_steps_found = max(p, na.rm = TRUE),
    n_genomes = n_distinct(Genome[p >= 50]), 
    .groups = "drop"
  )



# Force-show all modules by completing the grid
acet_phylum <- acet_phylum0 %>%
  mutate(module = factor(module, levels = module_order_acet)) %>%
  complete(
    phylum,
    module,
    fill = list(
      Percent_steps_found = 0,  # empty = 0% completeness (will be invisible with alpha mapping below)
      n_genomes = 0
    )
  ) %>%
  ungroup()

acet_phylum <- acet_phylum %>%
  group_by(phylum) %>%
  filter(any(Percent_steps_found >= 50, na.rm = TRUE)) %>%
  ungroup()

# Join genus abundance
acet_phylum <- acet_phylum %>%
  left_join(phylum_abun %>% filter(sample == "thermo"), by = "phylum")

acet_phylum <- acet_phylum %>%
  mutate(
    alpha = case_when(
      is.na(Percent_steps_found)        ~ 0,
      Percent_steps_found < 50          ~ 0, 
      TRUE ~ scales::rescale(Percent_steps_found, from = c(50, 100), to = c(0.15, 1))
    )
  )

phylum_labels <- phylum_abun %>%
  filter(sample == "thermo") %>%
  mutate(abun_lab = sprintf("%.1f%%", phylum_r_abund)) %>%
  semi_join(acet_phylum %>% distinct(phylum), by = "phylum")



acett <- ggplot(acet_phylum, aes(x = module, y = phylum)) +
  geom_tile(aes(alpha = alpha),
            fill = "palevioletred4", color = NA, width = 0.9, height = 0.9) +
  scale_alpha(
    name   = "Module\ncompleteness",
    limits = c(0, 1),
    breaks = scales::rescale(c(50, 75, 100), from = c(50, 100), to = c(0.15, 1)),
    labels = c("50%", "75%", "100%"),
    range  = c(0, 1)
  ) +
  guides(alpha = guide_legend(override.aes = list(fill = "palevioletred4"))) +
  geom_text(
    data = phylum_labels,
    aes(x = -Inf, y = phylum, label = abun_lab),
    inherit.aes = FALSE,
    hjust = 1,
    size = 3,
    colour = "black"
  ) +
  geom_text(aes(label = n_genomes), colour = "white", size = 3) +
  coord_cartesian(clip = "off") +
  theme_void() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 10),
    axis.text.y = element_text(size = 10, hjust = -0.35),
    axis.ticks  = element_line(color = "black"),
    axis.title  = element_blank(),
    legend.position = "right",
    panel.background = element_rect(fill = "white", color = NA),
    plot.background  = element_rect(fill = "white", color = NA),
    plot.margin = margin(t = 0, r = 20, b = 0, l = 60)
  )

acett


acet <- acetm | acett 


ggsave(filename = "higher_level/acetogenesis_phylum.png", plot = acet,
       width = 16, height = 8, dpi = 300)



```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
